packages:
  - "packages/*"
  - "examples/*/*"
  - "playground"
  - "fumadocs"
  - "docs"
  - "shared"
  - "tests"
preferWorkspacePackages: true
linkWorkspacePackages: true
gitChecks: false
storeDir: ./node_modules/.pnpm-store
publicHoistPattern:
  # We have been preferring to use `prosemirror-*` packages instead of `@tiptap/pm` packages
  - "prosemirror-*"
overrides:
  "@headlessui/react": "^2.2.4"
catalogs:
  automation:
    "@playwright/experimental-ct-react": 1.51.1
    "@playwright/test": 1.51.1
  build:
    "@vitejs/plugin-react": ^4.4.1
    rollup-plugin-webpack-stats: ^0.2.2
    vite: ^6
    vite-node: ^2.1.6
    vite-plugin-externalize-deps: ^0.8.0
    vite-plugin-inspect: 11.1.0
  cli:
    pncat: 0.4.1
  dev:
    "@ai-sdk/anthropic": ^1.2.12
    "@ai-sdk/google": ^1.2.20
    "@ai-sdk/groq": ^1.2.9
    "@ai-sdk/mistral": ^1.2.8
    "@ai-sdk/openai": ^1.3.22
    "@ai-sdk/openai-compatible": ^0.2.14
    "@liveblocks/react": ^2.24.3
    "@liveblocks/react-tiptap": ^2.24.3
    "@liveblocks/react-ui": ^2.24.3
    "@mswjs/interceptors": ^0.37.5
    "@mui/material": ^5.17.1
    "@radix-ui/colors": ^3.0.0
    "@react-email/components": ^0.0.36
    "@react-pdf/renderer": ^4.3.0
    "@testing-library/react": ^16.0.1
    "@tiptap/pm": ^2.12.0
    "@y-sweet/react": ^0.6.4
    "@zip.js/zip.js": ^2.7.57
    concurrently: 9.1.2
    glob: ^10.3.10
    headers-polyfill: ^4.0.3
    htmlfy: ^0.6.7
    jsdom: ^21.1.0
    msw: ^2.7.3
    msw-snapshot: ^5.2.0
    next-themes: 0.4.6
    next-validate-link: ^1.5.2
    pdf-to-img: ^4.2.0
    react: ^19.1.0
    react-dom: ^19.1.0
    react-element-to-jsx-string: ^17.0.0
    react-email: ^4.0.16
    serve: 14.2.4
    typescript: ^5.8.3
    undici: ^6
    wait-on: 8.0.3
    xml-formatter: ^3.6.3
    y-partykit: ^0.0.33
    yjs: ^13.6.27
  icons:
    "@heroicons/react": ^2.2.0
    "@mui/icons-material": ^5.16.1
    lucide-react: ^0.525.0
    react-icons: ^5.5.0
  lint:
    eslint: ^8.22.0
    eslint-config-react-app: ^7.0.0
    eslint-plugin-import: ^2.31.0
    prettier: ^3
    prettier-plugin-tailwindcss: ^0.6.11
    vite-plugin-eslint: ^1.8.1
  monorepo:
    "@nx/js": ^21.3.2
    nx: ^21.3.2
  network:
    "@aws-sdk/client-s3": ^3.609.0
    "@aws-sdk/s3-request-presigner": ^3.609.0
  node:
    rimraf: ^5.0.5
    tinyglobby: 0.2.12
  peer:
    "@hocuspocus/provider": ^2.15.2
    image-meta: ^0.2.1
  prod:
    "@ai-sdk/anthropic": ^1.2.11
    "@ai-sdk/google": ^1.2.20
    "@ai-sdk/groq": ^1.2.9
    "@ai-sdk/mistral": ^1.2.8
    "@ai-sdk/openai": ^1.3.22
    "@ai-sdk/openai-compatible": ^0.2.14
    "@ariakit/react": ^0.4.3
    "@blocknote/ariakit": latest
    "@blocknote/code-block": latest
    "@blocknote/core": latest
    "@blocknote/mantine": latest
    "@blocknote/prosemirror-suggest-changes": ^0.1.3
    "@blocknote/react": latest
    "@blocknote/server-util": latest
    "@blocknote/shadcn": latest
    "@blocknote/xl-ai": latest
    "@blocknote/xl-docx-exporter": latest
    "@blocknote/xl-email-exporter": latest
    "@blocknote/xl-multi-column": latest
    "@blocknote/xl-odt-exporter": latest
    "@blocknote/xl-pdf-exporter": latest
    "@emoji-mart/data": ^1.2.1
    "@emotion/react": ^11.11.4
    "@emotion/styled": ^11.11.5
    "@floating-ui/react": ^0.26.4
    "@fumadocs/mdx-remote": 1.3.0
    "@hono/node-server": ^1.13.7
    "@hookform/resolvers": ^3.6.0
    "@liveblocks/client": ^2.23.1
    "@liveblocks/core": ^2.23.1
    "@liveblocks/react": ^2.23.1
    "@liveblocks/react-blocknote": ^2.23.1
    "@liveblocks/react-tiptap": ^2.23.1
    "@liveblocks/react-ui": ^2.23.1
    "@mantine/core": ^7.17.3
    "@mantine/hooks": ^7.17.3
    "@mantine/utils": ^6.0.21
    "@mui/material": ^5.16.1
    "@polar-sh/better-auth": ^1.0.2
    "@polar-sh/nextjs": ^0.4.1
    "@polar-sh/sdk": ^0.34.2
    "@radix-ui/react-avatar": ^1.1.3
    "@radix-ui/react-dropdown-menu": ^2.0.6
    "@radix-ui/react-label": ^2.0.2
    "@radix-ui/react-popover": ^1.0.7
    "@radix-ui/react-select": ^2.0.0
    "@radix-ui/react-slot": ^1.0.2
    "@radix-ui/react-tabs": ^1.0.4
    "@radix-ui/react-toggle": ^1.0.3
    "@radix-ui/react-tooltip": ^1.0.7
    "@react-email/components": ^0.1.0
    "@react-email/render": ^1.1.2
    "@react-pdf/renderer": ^4.3.0
    "@sentry/nextjs": 9.14.0
    "@tiptap/core": ^2.12.0
    "@tiptap/extension-bold": ^2.11.5
    "@tiptap/extension-code": ^2.11.5
    "@tiptap/extension-gapcursor": ^2.11.5
    "@tiptap/extension-history": ^2.11.5
    "@tiptap/extension-horizontal-rule": ^2.11.5
    "@tiptap/extension-italic": ^2.11.5
    "@tiptap/extension-link": ^2.11.5
    "@tiptap/extension-paragraph": ^2.11.5
    "@tiptap/extension-strike": ^2.11.5
    "@tiptap/extension-table-cell": ^2.11.5
    "@tiptap/extension-table-header": ^2.11.5
    "@tiptap/extension-text": ^2.11.5
    "@tiptap/extension-underline": ^2.11.5
    "@tiptap/pm": ^2.12.0
    "@tiptap/react": ^2.12.0
    "@uppy/core": ^3.13.1
    "@uppy/dashboard": ^3.9.1
    "@uppy/drag-drop": ^3.1.1
    "@uppy/file-input": ^3.1.2
    "@uppy/image-editor": ^2.4.6
    "@uppy/progress-bar": ^3.1.1
    "@uppy/react": ^3.4.0
    "@uppy/screen-capture": ^3.2.0
    "@uppy/status-bar": ^3.1.1
    "@uppy/webcam": ^3.4.2
    "@uppy/xhr-upload": ^3.4.0
    "@vercel/analytics": ^1.5.0
    "@vercel/og": ^0.6.8
    "@y-sweet/react": ^0.6.3
    "@zip.js/zip.js": ^2.7.57
    ai: ^4.3.15
    babel-plugin-react-compiler: 19.1.0-rc.2
    better-auth: ^1.2.10
    better-sqlite3: ^11.10.0
    buffer: ^6.0.3
    classnames: 2.3.2
    docx: ^9.0.2
    emoji-mart: ^5.6.0
    framer-motion: ^11.13.4
    fumadocs-core: ^15.5.4
    fumadocs-docgen: ^2.0.1
    fumadocs-mdx: ^11.6.9
    fumadocs-twoslash: ^3.1.4
    fumadocs-typescript: ^4.0.6
    fumadocs-ui: ^15.5.4
    hast-util-from-dom: ^5.0.1
    hono: ^4.6.12
    image-meta: ^0.2.1
    import-in-the-middle: ^1.14.2
    jsdom: ^25.0.1
    next: ^15.4.1
    nodemailer: ^6.10.1
    partykit: ^0.0.115
    pg: ^8.15.5
    prosemirror-changeset: ^2.3.0
    prosemirror-dropcursor: ^1.8.2
    prosemirror-highlight: ^0.13.0
    prosemirror-model: ^1.25.1
    prosemirror-state: ^1.4.3
    prosemirror-tables: ^1.6.4
    prosemirror-transform: ^1.10.4
    prosemirror-view: ^1.38.1
    react: ^19.1.0
    react-dom: ^19.1.0
    react-email: ^4.0.16
    react-github-btn: ^1.4.0
    react-hook-form: ^7.52.0
    react-router-dom: ^6.20.0
    rehype-format: ^5.0.1
    rehype-parse: ^9.0.1
    rehype-remark: ^10.0.0
    rehype-stringify: ^10.0.1
    remark: ^15.0.1
    remark-gfm: ^4.0.1
    remark-mdx: ^3.1.0
    remark-parse: ^11.0.0
    remark-rehype: ^11.1.1
    remark-stringify: ^11.0.0
    require-in-the-middle: ^7.5.2
    ts-morph: 26.0.0
    twoslash: ^0.3.2
    unified: ^11.0.5
    uuid: ^8.3.2
    y-partykit: ^0.0.25
    y-prosemirror: ^1.3.4
    y-protocols: ^1.0.6
    yjs: ^13.6.27
    zustand: ^5.0.3
  script:
    tsx: ^4.6.2
  style:
    "@headlessui/react": ^2.2.4
    "@tailwindcss/postcss": ^4.1.10
    autoprefixer: ^10.4.19
    postcss: ^8.5.6
    tailwind-merge: ^2.3.0
    tailwindcss: ^4.1.10
    tailwindcss-animate: ^1.0.7
  syntax:
    "@shikijs/core": ^3.2.1
    "@shikijs/engine-javascript": ^3.2.1
    "@shikijs/langs": ^3.2.1
    "@shikijs/langs-precompiled": ^3.2.1
    "@shikijs/themes": ^3.2.1
    "@shikijs/types": ^3.2.1
    shiki: ^3.7.0
  test:
    "@vitest/runner": ^2.0.3
    "@vitest/ui": ^2.1.4
    jest-image-snapshot: ^6.4.0
    vitest: ^2.0.3
  types:
    "@types/better-sqlite3": 7.6.13
    "@types/diff": ^6.0.0
    "@types/emoji-mart": ^3.0.14
    "@types/hast": ^3.0.0
    "@types/jest-image-snapshot": ^6.4.0
    "@types/jsdom": ^21.1.7
    "@types/json-diff": ^1.0.3
    "@types/json-schema": ^7.0.15
    "@types/lodash.foreach": ^4.5.9
    "@types/lodash.groupby": ^4.6.9
    "@types/lodash.isequal": ^4.5.8
    "@types/lodash.merge": ^4.6.9
    "@types/mdx": ^2.0.13
    "@types/node": 22.15.2
    "@types/nodemailer": 6.4.17
    "@types/pg": 8.11.14
    "@types/react": ^19.1.8
    "@types/react-dom": ^19.1.6
    "@types/uuid": ^8.3.4
    "@typescript-eslint/eslint-plugin": ^5.5.0
    "@typescript-eslint/parser": ^5.5.0
  utils:
    class-variance-authority: ^0.7.0
    clsx: ^2.1.1
    lodash.isequal: ^4.5.0
    lodash.merge: ^4.6.2
    zod: ^3.25.67
