packages:
  - "packages/*"
  - "examples/*/*"
  - "playground"
  - "fumadocs"
  - "docs"
  - "shared"
  - "tests"
preferWorkspacePackages: true
linkWorkspacePackages: true
gitChecks: false
minimumReleaseAge: 1440
publicHoistPattern:
  # We have been preferring to use `prosemirror-*` packages instead of `@tiptap/pm` packages
  - "prosemirror-*"
overrides:
  "@headlessui/react": "^2.2.4"
  "@tiptap/core": "^3.0.0"
  "@tiptap/pm": "^3.0.0"
  "vitest": "4.1.7"
  "@vitest/runner": "4.1.7"
  "@y/y": "14.0.0-rc.23"
  "@y/prosemirror": "2.0.0-6"
  "lib0": "1.0.0-rc.22"
allowBuilds:
  "@parcel/watcher": true
  "@sentry/cli": true
  "@tailwindcss/oxide": true
  better-sqlite3: true
  esbuild: true
  msw: true
  unrs-resolver: true
  canvas: false
  sharp: false
  workerd: false
  leveldown: false
patchedDependencies:
  {
    "@y/prosemirror@2.0.0-6": patches/@y__prosemirror@2.0.0-6.patch,
    katex@0.16.47: patches/katex@0.16.47.patch,
  }
catalog:
  vite-plus: ^0.1.24
minimumReleaseAgeExclude:
  - vite-plus
  - lib0
  - "@y/y"
  - "@y/prosemirror"
  - "@voidzero-dev/*"
  - oxlint
  - "@oxlint/*"
  - oxlint-tsgolint
  - "@oxlint-tsgolint/*"
  - oxfmt
  - "@oxfmt/*"
