packages:
  - "packages/*"
  - "examples/*/*"
  - "playground"
  - "fumadocs"
  - "docs"
  - "shared"
  - "tests"
preferWorkspacePackages: true
linkWorkspacePackages: true
gitChecks: false
minimumReleaseAge: 1440
publicHoistPattern:
  # We have been preferring to use `prosemirror-*` packages instead of `@tiptap/pm` packages
  - "prosemirror-*"
overrides:
  "@headlessui/react": "^2.2.4"
  "@tiptap/core": "^3.0.0"
  "@tiptap/pm": "^3.0.0"
  "vitest": "catalog:"
  "@vitest/runner": "4.1.2"
  vite: "catalog:"
allowBuilds:
  "@parcel/watcher": true
  "@sentry/cli": true
  "@tailwindcss/oxide": true
  better-sqlite3: true
  esbuild: true
  msw: true
  nx: true
  unrs-resolver: true
  canvas: false
  sharp: false
  workerd: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/*"
  - oxlint
  - "@oxlint/*"
  - oxlint-tsgolint
  - "@oxlint-tsgolint/*"
  - oxfmt
  - "@oxfmt/*"
