packages:
  - "packages/*"
  - "examples/*/*"
  - "playground"
  - "fumadocs"
  - "docs"
  - "shared"
  - "tests"
preferWorkspacePackages: true
linkWorkspacePackages: true
gitChecks: false
storeDir: ./node_modules/.pnpm-store
publicHoistPattern:
  # We have been preferring to use `prosemirror-*` packages instead of `@tiptap/pm` packages
  - "prosemirror-*"
overrides:
  "@headlessui/react": "^2.2.4"
