packages:
  - "packages/*"
  - "examples/*/*"
  - "playground"
  - "docs"
  - "tests"
preferWorkspacePackages: true
linkWorkspacePackages: true
publicHoistPattern:
  # We have been preferring to use `prosemirror-*` packages instead of `@tiptap/pm` packages
  - "prosemirror-*"
