// generated by dev-scripts/examples/gen.ts
  export const examples = [
  {
    "group": "Advanced Examples",
    "projects": [
      {
        "slug": "alert-block",
        "pathFromRoot": "examples/alert-block",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Advanced Examples",
          "order": 1,
          "dependencies": {
            "@mantine/core": "^7.4.2",
            "react-icons": "^4.3.1"
          }
        },
        "title": "Alert Block"
      },
      {
        "slug": "custom-ui",
        "pathFromRoot": "examples/custom-ui",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Advanced Examples",
          "order": 1,
          "dependencies": {
            "@mantine/core": "^7.4.2"
          }
        },
        "title": "Making UI Elements From Scratch"
      }
    ]
  },
  {
    "group": "Basic Examples",
    "projects": [
      {
        "slug": "basic",
        "pathFromRoot": "examples/basic",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Basic Examples",
          "order": 1
        },
        "title": "basic"
      },
      {
        "slug": "block-manipulation",
        "pathFromRoot": "examples/block-manipulation",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Basic Examples",
          "order": 1
        },
        "title": "Block Manipulation"
      },
      {
        "slug": "blocks-block-objects",
        "pathFromRoot": "examples/blocks-block-objects",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Basic Examples",
          "order": 1
        },
        "title": "blocks-block-objects"
      },
      {
        "slug": "formatting-toolbar-buttons",
        "pathFromRoot": "examples/formatting-toolbar-buttons",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Basic Examples",
          "order": 1
        },
        "title": "Adding Formatting Toolbar Buttons"
      },
      {
        "slug": "side-menu-buttons",
        "pathFromRoot": "examples/side-menu-buttons",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Basic Examples",
          "order": 1,
          "dependencies": {
            "react-icons": "^4.3.1"
          }
        },
        "title": "Adding Side Menu Buttons"
      },
      {
        "slug": "side-menu-drag-handle-items",
        "pathFromRoot": "examples/side-menu-drag-handle-items",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Basic Examples",
          "order": 1,
          "dependencies": {
            "react-icons": "^4.3.1"
          }
        },
        "title": "Adding Drag Handle Menu Items"
      },
      {
        "slug": "slash-menu-items",
        "pathFromRoot": "examples/slash-menu-items",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Basic Examples",
          "order": 1,
          "dependencies": {
            "react-icons": "^4.3.1"
          }
        },
        "title": "Adding Slash Menu Items"
      },
      {
        "slug": "saving-loading",
        "pathFromRoot": "examples/saving-loading",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Basic Examples",
          "order": 2
        },
        "title": "Saving & Loading"
      },
      {
        "slug": "changing-font",
        "pathFromRoot": "examples/changing-font",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Basic Examples",
          "order": 3
        },
        "title": "Changing Font"
      },
      {
        "slug": "keyboard-shortcuts",
        "pathFromRoot": "examples/keyboard-shortcuts",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Basic Examples",
          "order": 5
        },
        "title": "Keyboard Shortcuts"
      }
    ]
  },
  {
    "group": "Advanced",
    "projects": [
      {
        "slug": "collaboration",
        "pathFromRoot": "examples/collaboration",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Advanced",
          "order": 1,
          "dependencies": {
            "y-partykit": "^0.0.10",
            "yjs": "^13.6.1"
          }
        },
        "title": "collaboration"
      }
    ]
  },
  {
    "group": "Custom Specs",
    "projects": [
      {
        "slug": "react-custom-blocks",
        "pathFromRoot": "examples/react-custom-blocks",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Custom Specs",
          "order": 2
        },
        "title": "react-custom-blocks"
      },
      {
        "slug": "react-custom-inline-content",
        "pathFromRoot": "examples/react-custom-inline-content",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Custom Specs",
          "order": 2
        },
        "title": "react-custom-inline-content"
      },
      {
        "slug": "react-custom-styles",
        "pathFromRoot": "examples/react-custom-styles",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Custom Specs",
          "order": 2
        },
        "title": "react-custom-styles"
      },
      {
        "slug": "react-vanilla-custom-blocks",
        "pathFromRoot": "examples/react-vanilla-custom-blocks",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Custom Specs",
          "order": 2
        },
        "title": "react-vanilla-custom-blocks"
      },
      {
        "slug": "react-vanilla-custom-inline-content",
        "pathFromRoot": "examples/react-vanilla-custom-inline-content",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Custom Specs",
          "order": 2
        },
        "title": "react-vanilla-custom-inline-content"
      },
      {
        "slug": "react-vanilla-custom-styles",
        "pathFromRoot": "examples/react-vanilla-custom-styles",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Custom Specs",
          "order": 2
        },
        "title": "react-vanilla-custom-styles"
      }
    ]
  }
];