// generated by dev-scripts/examples/gen.ts
  export const examples = {
  "basic": {
    "pathFromRoot": "examples/01-basic",
    "slug": "basic",
    "title": "Basic",
    "projects": [
      {
        "projectSlug": "minimal",
        "fullSlug": "basic/minimal",
        "pathFromRoot": "examples/01-basic/01-minimal",
        "config": {
          "playground": true,
          "docs": true
        },
        "title": "Basic Editor Setup",
        "group": {
          "pathFromRoot": "examples/01-basic",
          "slug": "basic"
        }
      },
      {
        "projectSlug": "block-objects",
        "fullSlug": "basic/block-objects",
        "pathFromRoot": "examples/01-basic/02-block-objects",
        "config": {
          "playground": true,
          "docs": true
        },
        "title": "Displaying Block Objects",
        "group": {
          "pathFromRoot": "examples/01-basic",
          "slug": "basic"
        }
      },
      {
        "projectSlug": "block-manipulation",
        "fullSlug": "basic/block-manipulation",
        "pathFromRoot": "examples/01-basic/03-block-manipulation",
        "config": {
          "playground": true,
          "docs": true
        },
        "title": "Block Manipulation",
        "group": {
          "pathFromRoot": "examples/01-basic",
          "slug": "basic"
        }
      },
      {
        "projectSlug": "saving-loading",
        "fullSlug": "basic/saving-loading",
        "pathFromRoot": "examples/01-basic/04-saving-loading",
        "config": {
          "playground": true,
          "docs": true,
          "shortTitle": "Saving & Loading"
        },
        "title": "Saving & Loading data",
        "group": {
          "pathFromRoot": "examples/01-basic",
          "slug": "basic"
        }
      },
      {
        "projectSlug": "file-uploading",
        "fullSlug": "basic/file-uploading",
        "pathFromRoot": "examples/01-basic/05-file-uploading",
        "config": {
          "playground": true,
          "docs": true
        },
        "title": "File / image uploading",
        "group": {
          "pathFromRoot": "examples/01-basic",
          "slug": "basic"
        }
      },
      {
        "projectSlug": "keyboard-shortcuts",
        "fullSlug": "basic/keyboard-shortcuts",
        "pathFromRoot": "examples/01-basic/06-keyboard-shortcuts",
        "config": {
          "playground": true,
          "docs": true
        },
        "title": "Keyboard Shortcuts",
        "group": {
          "pathFromRoot": "examples/01-basic",
          "slug": "basic"
        }
      }
    ]
  },
  "ui-components": {
    "pathFromRoot": "examples/02-ui-components",
    "slug": "ui-components",
    "title": "UI components",
    "projects": [
      {
        "projectSlug": "custom-ui",
        "fullSlug": "ui-components/custom-ui",
        "pathFromRoot": "examples/02-ui-components/custom-ui",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Advanced Examples",
          "order": 1,
          "dependencies": {
            "@mantine/core": "^7.5.0",
            "react-icons": "^4.3.1"
          }
        },
        "title": "Making UI Elements From Scratch",
        "group": {
          "pathFromRoot": "examples/02-ui-components",
          "slug": "ui-components"
        }
      },
      {
        "projectSlug": "formatting-toolbar-block-type-items",
        "fullSlug": "ui-components/formatting-toolbar-block-type-items",
        "pathFromRoot": "examples/02-ui-components/formatting-toolbar-block-type-items",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Basic Examples",
          "order": 1,
          "dependencies": {
            "react-icons": "^4.3.1"
          }
        },
        "title": "Adding Block Type Dropdown Items",
        "group": {
          "pathFromRoot": "examples/02-ui-components",
          "slug": "ui-components"
        }
      },
      {
        "projectSlug": "formatting-toolbar-buttons",
        "fullSlug": "ui-components/formatting-toolbar-buttons",
        "pathFromRoot": "examples/02-ui-components/formatting-toolbar-buttons",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Basic Examples",
          "order": 1
        },
        "title": "Adding Formatting Toolbar Buttons",
        "group": {
          "pathFromRoot": "examples/02-ui-components",
          "slug": "ui-components"
        }
      },
      {
        "projectSlug": "hyperlink-toolbar-buttons",
        "fullSlug": "ui-components/hyperlink-toolbar-buttons",
        "pathFromRoot": "examples/02-ui-components/hyperlink-toolbar-buttons",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Basic Examples",
          "order": 1
        },
        "title": "Adding Hyperlink Toolbar Buttons",
        "group": {
          "pathFromRoot": "examples/02-ui-components",
          "slug": "ui-components"
        }
      },
      {
        "projectSlug": "side-menu-buttons",
        "fullSlug": "ui-components/side-menu-buttons",
        "pathFromRoot": "examples/02-ui-components/side-menu-buttons",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Basic Examples",
          "order": 1,
          "dependencies": {
            "react-icons": "^4.3.1"
          }
        },
        "title": "Adding Block Side Menu Buttons",
        "group": {
          "pathFromRoot": "examples/02-ui-components",
          "slug": "ui-components"
        }
      },
      {
        "projectSlug": "side-menu-drag-handle-items",
        "fullSlug": "ui-components/side-menu-drag-handle-items",
        "pathFromRoot": "examples/02-ui-components/side-menu-drag-handle-items",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Basic Examples",
          "order": 1,
          "dependencies": {
            "react-icons": "^4.3.1"
          }
        },
        "title": "Adding Drag Handle Menu Items",
        "group": {
          "pathFromRoot": "examples/02-ui-components",
          "slug": "ui-components"
        }
      },
      {
        "projectSlug": "suggestion-menus-mentions",
        "fullSlug": "ui-components/suggestion-menus-mentions",
        "pathFromRoot": "examples/02-ui-components/suggestion-menus-mentions",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Basic Examples",
          "order": 1
        },
        "title": "Adding Suggestion Menu",
        "group": {
          "pathFromRoot": "examples/02-ui-components",
          "slug": "ui-components"
        }
      },
      {
        "projectSlug": "suggestion-menus-slash-menu-component",
        "fullSlug": "ui-components/suggestion-menus-slash-menu-component",
        "pathFromRoot": "examples/02-ui-components/suggestion-menus-slash-menu-component",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Basic Examples",
          "order": 1
        },
        "title": "Replacing Slash Menu Component",
        "group": {
          "pathFromRoot": "examples/02-ui-components",
          "slug": "ui-components"
        }
      },
      {
        "projectSlug": "suggestion-menus-slash-menu-items",
        "fullSlug": "ui-components/suggestion-menus-slash-menu-items",
        "pathFromRoot": "examples/02-ui-components/suggestion-menus-slash-menu-items",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Basic Examples",
          "order": 1,
          "dependencies": {
            "react-icons": "^4.3.1"
          }
        },
        "title": "Adding Slash Menu Items",
        "group": {
          "pathFromRoot": "examples/02-ui-components",
          "slug": "ui-components"
        }
      }
    ]
  },
  "theming": {
    "pathFromRoot": "examples/03-theming",
    "slug": "theming",
    "title": "Theming",
    "projects": [
      {
        "projectSlug": "changing-font",
        "fullSlug": "theming/changing-font",
        "pathFromRoot": "examples/03-theming/changing-font",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Basic Examples",
          "order": 3
        },
        "title": "Changing Font",
        "group": {
          "pathFromRoot": "examples/03-theming",
          "slug": "theming"
        }
      }
    ]
  },
  "cursor-selections": {
    "pathFromRoot": "examples/04-cursor-selections",
    "slug": "cursor-selections",
    "title": "Cursors & selections",
    "projects": [
      {
        "projectSlug": "selection-blocks",
        "fullSlug": "cursor-selections/selection-blocks",
        "pathFromRoot": "examples/04-cursor-selections/selection-blocks",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Basic Examples",
          "order": 1
        },
        "title": "Highlighting Blocks in Selection",
        "group": {
          "pathFromRoot": "examples/04-cursor-selections",
          "slug": "cursor-selections"
        }
      },
      {
        "projectSlug": "text-cursor-block",
        "fullSlug": "cursor-selections/text-cursor-block",
        "pathFromRoot": "examples/04-cursor-selections/text-cursor-block",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Basic Examples",
          "order": 1
        },
        "title": "Highlighting Block with the Text Cursor",
        "group": {
          "pathFromRoot": "examples/04-cursor-selections",
          "slug": "cursor-selections"
        }
      }
    ]
  },
  "custom-schema": {
    "pathFromRoot": "examples/05-custom-schema",
    "slug": "custom-schema",
    "title": "Custom schemas",
    "projects": [
      {
        "projectSlug": "alert-block",
        "fullSlug": "custom-schema/alert-block",
        "pathFromRoot": "examples/05-custom-schema/alert-block",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Advanced Examples",
          "order": 1,
          "dependencies": {
            "@mantine/core": "^7.5.0",
            "react-icons": "^4.3.1"
          }
        },
        "title": "Alert Block",
        "group": {
          "pathFromRoot": "examples/05-custom-schema",
          "slug": "custom-schema"
        }
      },
      {
        "projectSlug": "font-style",
        "fullSlug": "custom-schema/font-style",
        "pathFromRoot": "examples/05-custom-schema/font-style",
        "config": {
          "playground": true,
          "docs": true,
          "group": "Advanced Examples",
          "order": 1
        },
        "title": "Font Style",
        "group": {
          "pathFromRoot": "examples/05-custom-schema",
          "slug": "custom-schema"
        }
      },
      {
        "projectSlug": "react-custom-blocks",
        "fullSlug": "custom-schema/react-custom-blocks",
        "pathFromRoot": "examples/05-custom-schema/react-custom-blocks",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Custom Specs",
          "order": 2
        },
        "title": "Custom Blocks - React API",
        "group": {
          "pathFromRoot": "examples/05-custom-schema",
          "slug": "custom-schema"
        }
      },
      {
        "projectSlug": "react-custom-inline-content",
        "fullSlug": "custom-schema/react-custom-inline-content",
        "pathFromRoot": "examples/05-custom-schema/react-custom-inline-content",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Custom Specs",
          "order": 2
        },
        "title": "Custom Inline Content - React API",
        "group": {
          "pathFromRoot": "examples/05-custom-schema",
          "slug": "custom-schema"
        }
      },
      {
        "projectSlug": "react-custom-styles",
        "fullSlug": "custom-schema/react-custom-styles",
        "pathFromRoot": "examples/05-custom-schema/react-custom-styles",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Custom Specs",
          "order": 2
        },
        "title": "Custom Styles - React API",
        "group": {
          "pathFromRoot": "examples/05-custom-schema",
          "slug": "custom-schema"
        }
      }
    ]
  },
  "collaboration": {
    "pathFromRoot": "examples/06-collaboration",
    "slug": "collaboration",
    "title": "Collaboration",
    "projects": [
      {
        "projectSlug": "partykit",
        "fullSlug": "collaboration/partykit",
        "pathFromRoot": "examples/06-collaboration/partykit",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Advanced",
          "order": 1,
          "dependencies": {
            "y-partykit": "^0.0.10",
            "yjs": "^13.6.1"
          }
        },
        "title": "Collaboration",
        "group": {
          "pathFromRoot": "examples/06-collaboration",
          "slug": "collaboration"
        }
      }
    ]
  },
  "interoperability": {
    "pathFromRoot": "examples/07-interoperability",
    "slug": "interoperability",
    "title": "Interoperability",
    "projects": [
      {
        "projectSlug": "converting-blocks-to-html",
        "fullSlug": "interoperability/converting-blocks-to-html",
        "pathFromRoot": "examples/07-interoperability/01-converting-blocks-to-html",
        "config": {
          "playground": true,
          "docs": true
        },
        "title": "Converting Blocks to HTML",
        "group": {
          "pathFromRoot": "examples/07-interoperability",
          "slug": "interoperability"
        }
      },
      {
        "projectSlug": "converting-blocks-from-html",
        "fullSlug": "interoperability/converting-blocks-from-html",
        "pathFromRoot": "examples/07-interoperability/02-converting-blocks-from-html",
        "config": {
          "playground": true,
          "docs": true
        },
        "title": "Parsing HTML to Blocks",
        "group": {
          "pathFromRoot": "examples/07-interoperability",
          "slug": "interoperability"
        }
      },
      {
        "projectSlug": "converting-blocks-to-md",
        "fullSlug": "interoperability/converting-blocks-to-md",
        "pathFromRoot": "examples/07-interoperability/03-converting-blocks-to-md",
        "config": {
          "playground": true,
          "docs": true
        },
        "title": "Converting Blocks to Markdown",
        "group": {
          "pathFromRoot": "examples/07-interoperability",
          "slug": "interoperability"
        }
      },
      {
        "projectSlug": "converting-blocks-from-md",
        "fullSlug": "interoperability/converting-blocks-from-md",
        "pathFromRoot": "examples/07-interoperability/04-converting-blocks-from-md",
        "config": {
          "playground": true,
          "docs": true
        },
        "title": "Parsing Markdown to Blocks",
        "group": {
          "pathFromRoot": "examples/07-interoperability",
          "slug": "interoperability"
        }
      }
    ]
  },
  "vanilla-js": {
    "pathFromRoot": "examples/08-vanilla-js",
    "slug": "vanilla-js",
    "title": "Vanilla JS",
    "projects": [
      {
        "projectSlug": "react-vanilla-custom-blocks",
        "fullSlug": "vanilla-js/react-vanilla-custom-blocks",
        "pathFromRoot": "examples/08-vanilla-js/react-vanilla-custom-blocks",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Custom Specs",
          "order": 2
        },
        "title": "Custom Blocks - Vanilla JS API",
        "group": {
          "pathFromRoot": "examples/08-vanilla-js",
          "slug": "vanilla-js"
        }
      },
      {
        "projectSlug": "react-vanilla-custom-inline-content",
        "fullSlug": "vanilla-js/react-vanilla-custom-inline-content",
        "pathFromRoot": "examples/08-vanilla-js/react-vanilla-custom-inline-content",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Custom Specs",
          "order": 2
        },
        "title": "Custom Inline Content - Vanilla JS API",
        "group": {
          "pathFromRoot": "examples/08-vanilla-js",
          "slug": "vanilla-js"
        }
      },
      {
        "projectSlug": "react-vanilla-custom-styles",
        "fullSlug": "vanilla-js/react-vanilla-custom-styles",
        "pathFromRoot": "examples/08-vanilla-js/react-vanilla-custom-styles",
        "config": {
          "playground": true,
          "docs": false,
          "group": "Custom Specs",
          "order": 2
        },
        "title": "Custom Styles - Vanilla JS API",
        "group": {
          "pathFromRoot": "examples/08-vanilla-js",
          "slug": "vanilla-js"
        }
      }
    ]
  }
};