export type SupportedLanguageConfig = {
  id: string;
  name: string;
  match: string[];
};

export const defaultSupportedLanguages: SupportedLanguageConfig[] = [
  { id: "text", name: "Plain Text", match: ["text", "txt", "plain"] },
  { match: ["c"], id: "c", name: "C" },
  { match: ["cpp", "c++"], id: "cpp", name: "C++" },
  { match: ["css"], id: "css", name: "CSS" },
  { match: ["glsl"], id: "glsl", name: "GLSL" },
  { match: ["graphql", "gql"], id: "graphql", name: "GraphQL" },
  { match: ["haml"], id: "haml", name: "Ruby Haml" },
  { match: ["html"], id: "html", name: "HTML" },
  { match: ["java"], id: "java", name: "Java" },
  { match: ["javascript", "js"], id: "javascript", name: "JavaScript" },
  { match: ["json"], id: "json", name: "JSON" },
  { match: ["jsonc"], id: "jsonc", name: "JSON with Comments" },
  { match: ["jsonl"], id: "jsonl", name: "JSON Lines" },
  { match: ["jsx"], id: "jsx", name: "JSX" },
  { match: ["julia", "jl"], id: "julia", name: "Julia" },
  { match: ["less"], id: "less", name: "Less" },
  { match: ["markdown", "md"], id: "markdown", name: "Markdown" },
  { match: ["mdx"], id: "mdx", name: "MDX" },
  { match: ["php"], id: "php", name: "PHP" },
  { match: ["postcss"], id: "postcss", name: "PostCSS" },
  { match: ["pug", "jade"], id: "pug", name: "Pug" },
  { match: ["python", "py"], id: "python", name: "Python" },
  { match: ["r"], id: "r", name: "R" },
  { match: ["regexp", "regex"], id: "regexp", name: "RegExp" },
  { match: ["sass"], id: "sass", name: "Sass" },
  { match: ["scss"], id: "scss", name: "SCSS" },
  {
    match: ["shellscript", "bash", "sh", "shell", "zsh"],
    id: "shellscript",
    name: "Shell",
  },
  { match: ["sql"], id: "sql", name: "SQL" },
  { match: ["svelte"], id: "svelte", name: "Svelte" },
  { match: ["typescript", "ts"], id: "typescript", name: "TypeScript" },
  { match: ["vue"], id: "vue", name: "Vue" },
  { match: ["vue-html"], id: "vue-html", name: "Vue HTML" },
  { match: ["wasm"], id: "wasm", name: "WebAssembly" },
  { match: ["wgsl"], id: "wgsl", name: "WGSL" },
  { match: ["xml"], id: "xml", name: "XML" },
  { match: ["yaml", "yml"], id: "yaml", name: "YAML" },
  { id: "tsx", name: "TSX", match: ["tsx", "typescriptreact"] },
  { id: "haskell", name: "Haskell", match: ["haskell", "hs"] },
  { id: "csharp", name: "C#", match: ["c#", "csharp", "cs"] },
  { id: "latex", name: "LaTeX", match: ["latex"] },
  { id: "lua", name: "Lua", match: ["lua"] },
  { id: "mermaid", name: "Mermaid", match: ["mermaid", "mmd"] },
  { id: "ruby", name: "Ruby", match: ["ruby", "rb"] },
  { id: "rust", name: "Rust", match: ["rust", "rs"] },
  { id: "scala", name: "Scala", match: ["scala"] },
  { id: "swift", name: "Swift", match: ["swift"] },
  { id: "kotlin", name: "Kotlin", match: ["kotlin", "kt", "kts"] },
  { id: "objective-c", name: "Objective C", match: ["objective-c", "objc"] },
];
