#set document(title: "Diagram", author: "")
#set text(font: "Inter 18pt", size: 12pt, lang: "en")
#set page(paper: "a4", margin: 48pt)
#set par(leading: 0.78em, spacing: 0pt, justify: false)
#set block(spacing: 0pt)
#set list(spacing: 0pt)
#set enum(spacing: 0pt)
#set heading(numbering: none)
#show heading: set text(weight: 700)
#show heading.where(level: 1): set text(size: 36pt)
#show heading.where(level: 2): set text(size: 24pt)
#show heading.where(level: 3): set text(size: 15.6pt)
#show heading.where(level: 4): set text(size: 12pt)
#show heading.where(level: 5): set text(size: 10.8pt)
#show heading.where(level: 6): set text(size: 9.6pt)
#show raw: set text(font: "Geist Mono")
#show raw.where(block: true): it => block(width: 100%, inset: 12pt, radius: 3pt, fill: luma(248), stroke: 0.5pt + luma(210), it)
#show quote.where(block: true): it => block(inset: (left: 14pt, y: 4pt), stroke: (left: 2pt + rgb("#7D797A")), text(fill: rgb("#7D797A"), it.body))
#set figure(numbering: none)
#show figure.caption: set text(size: 9.6pt, fill: luma(110))
#show link: set text(fill: rgb("#0b6e99"))
#let _cb-unchecked = box(baseline: 0.24em, width: 0.9em, height: 0.9em, radius: 2pt, stroke: 0.08em + luma(148), fill: white)
#let _cb-checked = box(baseline: 0.24em, width: 0.9em, height: 0.9em, radius: 2pt, stroke: 0.08em + rgb("#3183c8"), fill: rgb("#3183c8"), place(center + horizon, {
  box(move(dx: -0.11em, dy: 0.05em, rotate(45deg, line(length: 0.2em, stroke: white + 0.11em))))
  box(move(dx: 0.02em, dy: -0.04em, rotate(-45deg, line(length: 0.38em, stroke: white + 0.11em))))
}))

#block(width: 100%, inset: (top: 6.9pt, bottom: 6.9pt))[#[#show figure: set align(center); #figure(image("/assets/asset-0.png", width: 75.0pt), alt: "graph TD\n  A[Start] --> B[End]")]]
