import { defineConfig } from "vite-plus";

export default defineConfig({
  run: {
    tasks: {
      // Validate that all `/examples/...` (and other) links referenced in the
      // docs resolve to a real page. The example pages under
      // `content/examples/**` are generated by the dev-scripts `gen:docs`
      // task, so we depend on it here. Declaring the dependency as a task
      // (instead of chaining `vp run gen && node validate-links.mjs` as a
      // package.json script) lets Vite Task's caching archive & restore the
      // generated files: on a cache hit the example pages are restored before
      // this task runs, and on a fresh run the dependency fully completes
      // before validation starts. This avoids a race where validate-links ran
      // before `gen:docs` finished writing `docs/content/examples/**`.
      test: {
        command: "node validate-links.mjs",
        dependsOn: ["@blocknote/dev-scripts#gen:docs"],
      },
    },
  },
});
